---
title: "R Notebook"
output: html_notebook
---

```{r}
library(mgcv)
library(ncdf4)
library(ggplot2)

# =========================================================
# Funktion: GAM trainieren
# =========================================================

train_emulator <- function(response, var_list, family, cal_timesteps){
  
  # -------------------------------------------------------
  # Kovariaten extrahieren (nur gültige Punkte)
  # -------------------------------------------------------
  covar <- do.call(cbind.data.frame, lapply(var_list, function(x){
    x[cal_timesteps,,][which(!is.na(response[cal_timesteps,,]))]
  }))
  
  names(covar) <- names(var_list)
  
  # -------------------------------------------------------
  # Modellformel: Tensorprodukt-Smoother
  # -------------------------------------------------------
  # te(...) = flexible nichtlineare Interaktion aller Variablen
  formula <- formula(
    paste0("tf ~ te(", paste(names(covar), collapse = ","), ")")
  )
  
  # -------------------------------------------------------
  # Datensatz für GAM
  # -------------------------------------------------------
  data <- cbind.data.frame(
    tf = response[cal_timesteps,,][which(!is.na(response[cal_timesteps,,]))],
    covar
  )
  
  # -------------------------------------------------------
  # GAM fitten
  # -------------------------------------------------------
  emulator <- mgcv::gam(formula, data = data, family = family)
  
  return(emulator)
}

```

```{r}

# =========================================================
# Funktion: Modell evaluieren + Residuen berechnen
# =========================================================

evaluate_emulator <- function(emulator, response, var_list, val_timesteps) {
  
  # -------------------------------------------------------
  # Kovariaten für Validierungsdaten
  # -------------------------------------------------------
  covar <- do.call(cbind.data.frame, lapply(var_list, function(x){
    x[val_timesteps,,][which(!is.na(response[val_timesteps,,]))]
  }))
  
  names(covar) <- names(var_list)
  
  # -------------------------------------------------------
  # Datensatz (nur gültige Punkte)
  # -------------------------------------------------------
  data <- cbind.data.frame(
    tf = response[val_timesteps,,][which(!is.na(response[val_timesteps,,]))],
    covar
  )
  
  # -------------------------------------------------------
  # Vorhersagen des GAM
  # -------------------------------------------------------
  predict_data <- predict(emulator, type = "response", newdata = data)
  
  # =======================================================
  # Residuen 
  # =======================================================
  
  # r = y - y_hat
  residuals_vec <- data$tf - predict_data
  
  # -------------------------------------------------------
  # Vorhersagen zurück ins Raum-Zeit-Array
  # -------------------------------------------------------
  datafield_predict <- response[val_timesteps,,]
  datafield_predict[which(!is.na(datafield_predict))] <- predict_data
  
  # -------------------------------------------------------
  # Residuen zurück ins Raum-Zeit-Array
  # -------------------------------------------------------
  residual_field <- response[val_timesteps,,]
  residual_field[which(!is.na(residual_field))] <- residuals_vec
  
  # =======================================================
  # Ortsweise Fehlermetriken
  # =======================================================
  
  rmse_field <- array(NA, dim = dim(datafield_predict)[2:3])
  mae_field  <- array(NA, dim = dim(datafield_predict)[2:3])
  mean_residual_field <- array(NA, dim = dim(datafield_predict)[2:3])
  
  for (i in 1:dim(rmse_field)[1]) {
    for (j in 1:dim(rmse_field)[2]) {
      
      obs_ij  <- response[val_timesteps, i, j]
      pred_ij <- datafield_predict[, i, j]
      res_ij  <- residual_field[, i, j]
      
      # RMSE
      rmse_field[i, j] <- suppressWarnings(
        sqrt(mean((obs_ij - pred_ij)^2, na.rm = TRUE))
      )
      
      # MAE
      mae_field[i, j] <- suppressWarnings(
        mean(abs(obs_ij - pred_ij), na.rm = TRUE)
      )
      
      #  Bias
      mean_residual_field[i, j] <- suppressWarnings(
        mean(res_ij, na.rm = TRUE)
      )
    }
  }
  
  # -------------------------------------------------------
  # Rückgabe aller wichtigen Objekte
  # -------------------------------------------------------
  list(
    results = data.frame(
      rmse = sqrt(mean((predict_data - data$tf)^2)),
      mae = mean(abs(predict_data - data$tf)),
      Expl_var = 1 - mean((predict_data - data$tf)^2) / var(data$tf)
    ),
    
    predictions = predict_data,        s
    residuals_vec = residuals_vec,     # für Histogramm etc.
    residual_field = residual_field,   # Raum-Zeit-Analyse
    
    rmse_field = rmse_field,
    mae_field = mae_field,
    mean_residual_field = mean_residual_field,
    
    data = data
  )
}

```

```{r}
# =========================================================
# Daten laden
# =========================================================

nc <- nc_open("MPI_V3_G_TreeCover_mean_time.nc")
lon <- ncvar_get(nc,"lon")
lat <- rev(ncvar_get(nc,"lat"))
time <- ncvar_get(nc,"time")[1:40]
tf <- aperm(ncvar_get(nc,"cover_fract")[,48:1,1:40],c(3,1,2))
nc_close(nc)

nc <- nc_open("MPI_V3_G_Pann_mean_time.nc")
time_tmp <- ncvar_get(nc,"time")
precip <- aperm(ncvar_get(nc,"precip")[,48:1,which(time_tmp %in% time)],c(3,1,2))
nc_close(nc)

nc <- nc_open("MPI_V3_G_tcold_mean_time.nc")
time_tmp <- ncvar_get(nc,"time")
tcold <- aperm(ncvar_get(nc,"temp2")[,48:1,which(time_tmp %in% time)],c(3,1,2))
nc_close(nc)

nc <- nc_open("MPI_V3_G_twarm_mean_time.nc")
time_tmp <- ncvar_get(nc,"time")
twarm <- aperm(ncvar_get(nc,"temp2")[,48:1,which(time_tmp %in% time)],c(3,1,2))
nc_close(nc)

```

```{r}
# =========================================================
# Train/Test Split
# =========================================================

training_data_fraction <- 0.5

cal_timesteps <- seq(1,length(time),by=1/training_data_fraction)

if (training_data_fraction == 1) {
  val_timesteps <- cal_timesteps
} else {
  val_timesteps <- (1:length(time))[!(1:length(time)) %in% cal_timesteps]
}

# =========================================================
# Modell fitten
# =========================================================

var_list <- list(precip=precip, tcold=tcold, twarm=twarm)
response <- tf

emulator <- train_emulator(
  response,
  var_list = var_list,
  family = binomial,
  cal_timesteps = cal_timesteps
)

emulator
```

```{r}
# =========================================================
# Evaluation + Residuen
# =========================================================

eval_out <- evaluate_emulator(
  emulator,
  response = response,
  var_list = var_list,
  val_timesteps = val_timesteps
)

# =========================================================
# Residualanalyse
# =========================================================

cat("Globale Modellgüte:\n")
print(eval_out$results)

cat("\nZusammenfassung der Residuen:\n")
print(summary(eval_out$residuals_vec))

```

```{r}
# ---------------------------------------------------------
# Histogramm
# ---------------------------------------------------------
ggplot(data.frame(res = eval_out$residuals_vec), aes(res)) +
  geom_histogram(bins = 50) +
  ggtitle("Histogramm der Residuen")

```

```{r}
# ---------------------------------------------------------
# QQ-Plot
# ---------------------------------------------------------
qqnorm(eval_out$residuals_vec)
qqline(eval_out$residuals_vec, col = "red")
```

```{r}
# ---------------------------------------------------------
# Residuen vs Vorhersage
# ---------------------------------------------------------
ggplot(data.frame(pred = eval_out$predictions,
                  res = eval_out$residuals_vec),
       aes(pred, res)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, col = "red") +
  ggtitle("Residuals vs Prediction")


```


```{r}
# ---------------------------------------------------------
# Beobachtet vs Vorhersage
# ---------------------------------------------------------
ggplot(data.frame(obs = eval_out$data$tf,
                  pred = eval_out$predictions),
       aes(obs, pred)) +
  geom_point(alpha = 0.2) +
  geom_abline() +
  ggtitle("Observed vs Predicted")



```

```{r}
# =========================================================
# Raumstruktur
# =========================================================

# Mittlerer Bias im Raum
image(lon, lat, eval_out$mean_residual_field,
      main = "Mittlere Residuenkarte")

# Fehlerstärke im Raum
image(lon, lat, eval_out$rmse_field,
      main = "RMSE-Karte")

# Residuen für einen Zeitpunkt
image(lon, lat, eval_out$residual_field[1,,],
      main = "Residuenkarte (Zeitpunkt 1)")

```

```{r}
# =========================================================
# Zeitstruktur
# =========================================================

# Finde Ort mit vielen gültigen Werten
valid_counts <- apply(!is.na(eval_out$residual_field), c(2,3), sum)

# Ort mit meisten Beobachtungen
idx <- which(valid_counts == max(valid_counts), arr.ind = TRUE)

i_best <- idx[1,1]
j_best <- idx[1,2]

res_vec <- eval_out$residual_field[,i_best,j_best]
time_vec <- time[val_timesteps]

valid_idx <- which(!is.na(res_vec))

plot(time_vec[valid_idx],
     res_vec[valid_idx],
     type = "b",
     main = "Residualzeitreihe",
     xlab = "Zeit",
     ylab = "Residual")

acf(res_vec[valid_idx],
    main = "ACF der Residuen")
```

